framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    # @see Transaction will be started any time you dispatching message
                    - validation
                    - doctrine_transaction

            query.bus:
                middleware:
                    - validation

        transports:
            sync: 'sync://'
