security:
    encoders:
        App\User\Domain\Model\User: 'auto'

    providers:
        database_users:
            entity: { class: App\User\Domain\Model\User, property: username }

    # https://symfony.com/doc/current/security.html#a-authentication-firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # this firewall applies to all URLs
            pattern: ^/

            # but the firewall does not require login on every page
            # denying access is done in access_control or in your controllers
            anonymous: true
            lazy: true

            provider: database_users
    access_control:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
