version: '3.7'

volumes:
    database:
    redis:

services:
    php-fpm:
        image: php-fpm
        restart: always
        build:
            context: ./
            target: backend
        expose:
            - 9000
        ports:
            - 9000
        links:
            - mysql
            - redis
        depends_on:
            - mysql
            - redis
        volumes:
            - ./:/var/www/html

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
            - 3306
        ports:
            - 3306
        environment:
            MYSQL_DATABASE: symfony
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - database:/var/lib/mysql

    nginx:
        image: nginx
        build:
            context: ./
            target: frontend
        links:
            - php-fpm
        depends_on:
            - php-fpm
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites-available/:/etc/nginx/sites-available
            - ./public:/var/www/html/public

    redis:
        image: redis:6-alpine
        volumes:
            - redis:/data